### ISSUE TITLE
Return str instead of bytes from enforce

### ISSUE THREAD

**Issue by horazont** [byllyfish/precis_i18n#2]
Is there a rationale for returning bytes from enforce? 

From the name alone it would appear to me that enforce would apply the rules and return the text, not the text encoded in UTF-8.

I would appreciate a function which returns the enforce-d text without encoding it. Of course it’s possible to decode it right away, but that reduces readability.

**Comment by byllyfish** [comment]
My original thinking was that `enforce` would get the string ready for bit-by-bit comparison as a byte string. However, I do agree it makes more sense to return the text. I will change the code to do so.

**Comment by byllyfish** [comment]
The codec API will continue to return utf-8 because str.encode() must return bytes. The `enforce` API will return a string.

**Comment by byllyfish** [comment]
In version 0.5, the `enforce` method now returns a Unicode string instead of UTF-8 bytes.

**Comment by horazont** [comment]
Cool thanks! Having the codec API return UTF-8 is also great, because that what it is for.
