### ISSUE TITLE
"test/derived-props-11.0.txt" missing in release 1.0

### ISSUE THREAD

**Issue by maribu** [byllyfish/precis_i18n#6]
Hi,

the unit tests are failing for the release 1.0 as the file `test/derived-props-11.0.txt` is not included. It has been added in https://github.com/byllyfish/precis_i18n/commit/f68b66a80fa36ff1004f5a88696edb424a75dd76

Adding that file manually solves the issue. Maybe you could re-pack the release to add the missing file (and release that as 1.0.1)?

Kind regards,
Marian

**Comment by byllyfish** [comment]
Thanks for the feedback!

I will push a 1.0.1 release today.

**Comment by byllyfish** [comment]
1.0.1 released to github and pypi.

**Comment by maribu** [comment]
Thanks for the fast fix :-)
